//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TestAR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean PullTheTrigger
        {
            get
            {
                return SteamVR_Actions.testAR_PullTheTrigger;
            }
        }
        
        public virtual SteamVR_Action_Single PressTheTrigger
        {
            get
            {
                return SteamVR_Actions.testAR_PressTheTrigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.testAR_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean ModeChange
        {
            get
            {
                return SteamVR_Actions.testAR_ModeChange;
            }
        }
        
        public virtual SteamVR_Action_Boolean CenterDown
        {
            get
            {
                return SteamVR_Actions.testAR_CenterDown;
            }
        }
        
        public virtual SteamVR_Action_Vector2 CenterNavigate
        {
            get
            {
                return SteamVR_Actions.testAR_CenterNavigate;
            }
        }
        
        public virtual SteamVR_Action_Boolean LeftSideDown
        {
            get
            {
                return SteamVR_Actions.testAR_LeftSideDown;
            }
        }
    }
}
